packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  # all packages in subdirs of components/
  - "components/**"
  # api base axios
  - "apis/**"
  # 工具类
  - "utils/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
